### ISSUE TITLE
Feature Request: Video Support

### ISSUE THREAD

**Issue by mo8Zomo0** [chrta/sip_call#13]
There are some board with video cams. Would it be possible to integrate a video feed from the camera module?

**Comment by chrta** [comment]
Can you collect some information regarding sip protocol and the other necessary protocols (sdp support?) and codecs that are necessary for this?
Is there any other project already doing this?

**Comment by chrta** [comment]
Closing this because no feedback provided and there seems to be no further interest (and time)...
