### ISSUE TITLE
No bell after Cancel

### ISSUE THREAD

**Issue by Flattermann78** [chrta/sip_call#7]
In case you just cancel a call (red button) instead of answering the call and then cancel the call, it is not possible to ring again. It seems that the state machine get stuck somewhere.

**Comment by chrta** [comment]
I will have a look in a few days.

**Comment by chrta** [comment]
With the current master branch it is working for me, see log at the bottom.
But i get a 603 DECLINE when i press the red button on my phone. Could you post your log, with the received and sent messages, starting from the button press?
Either sent the log level to verbose (produces a lot of data) or set it to info and edit the file components/sip_client/include/sip_client/lwip_udp_client.h around line 220 and 233.

~~~
I (94728) UdpSocket: Received following data: SIP/2.0 603 Decline
Via: SIP/2.0/UDP 192.168.180.35:5060;branch=z9hG4bK-220137366;rport=5060
From: "Dev-Board" <sip:esp32-dev@192.168.180.1>;tag=147699711
To: <sip:**613@192.168.180.1>;tag=FDD7685127E137DC
Call-ID: 733414765@192.168.180.35
CSeq: 1481765942 INVITE
User-Agent: FRITZ!OS
Content-Length: 0


I (94728) UdpSocket: Received following data: �
I (94748) SipClient: Parsing the packet ok, reply code=7
I (94758) UdpSocket: Sending following data: ACK sip:**613@192.168.180.1 SIP/2.0
CSeq: 1481765942 ACK
Call-ID: 733414765@192.168.180.35
Max-Forwards: 70
User-Agent: sip-client/0.0.1
From: "esp32-dev" <sip:esp32-dev@192.168.180.1>;tag=147699711
Via: SIP/2.0/UDP 192.168.180.35:5060;branch=z9hG4bK-220137366;rport
To: <sip:**613@192.168.180.1>;tag=FDD7685127E137DC
Content-Length: 0


I (94768) UdpSocket: Received following data: �
I (94798) SipClient: New state 7 -> 3

~~~

**Comment by chrta** [comment]
I found a few issues in the code that might be fixed now, please retest.

**Comment by Flattermann78** [comment]
Solved! Thank you!
