### ISSUE TITLE
GPIO not doing anything

### ISSUE THREAD

**Issue by versamodule** [chrta/sip_call#8]
I have compiled this and it is running, The last thing I get on the serial console is: 
I (7227) main: SIP client initialized successfully

I have configured GPIO to be 5 in menuconfig, but tacking it from high to low and back to high does nothing. Any ideas ?

**Comment by chrta** [comment]
Is it working if you configure GPIO 0?

The gpio configuration is done here: https://github.com/chrta/sip_call/blob/master/main/button_handler.h#L61 There should be nothing special about it.

**Comment by versamodule** [comment]
I didn't modify any of the code, and saw that it was using GPIO 0 in menuconfig. The first time I left that unchanged and it did not trigger, That is when I tried GPIO 5 with the same results.

**Comment by chrta** [comment]
I do not think that  is a problem with GPIOs. If you activated info loglevel, you should see several messages from https://github.com/chrta/sip_call/blob/master/components/sip_client/include/sip_client/sip_client.h#L716
After booting, joining the WLAN and successful DHCP request (this worked according to your log message) , the ESP32 should be in state 3 (registered), that means that the ESP32 successfully connected to the SIP server.

Maybe you could increase the log level in "make menuconfig" and post the log.

**Comment by versamodule** [comment]
Thanks for the tip, I will try that.

**Comment by chrta** [comment]
No Feedback for a few months...
